#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pluginRoot = resolve(__dirname, "..");
const templatePath = join(
  pluginRoot,
  "skills",
  "autopilot-loop",
  "assets",
  "state-template.json",
);

function parseArgs(argv) {
  const [command = "help", ...rest] = argv;
  const flags = { _: [] };
  for (let i = 0; i < rest.length; i += 1) {
    const item = rest[i];
    if (!item.startsWith("--")) {
      flags._.push(item);
      continue;
    }
    const key = item.slice(2);
    const next = rest[i + 1];
    if (i + 1 >= rest.length || next.startsWith("--")) {
      flags[key] = true;
    } else {
      flags[key] = next;
      i += 1;
    }
  }
  return { command, flags };
}

function statePaths(dirFlag) {
  const root = resolve(dirFlag || process.cwd());
  const loopDir = join(root, ".agent-loop");
  return {
    root,
    loopDir,
    iterationsDir: join(loopDir, "iterations"),
    statePath: join(loopDir, "state.json"),
  };
}

function readJson(path) {
  return JSON.parse(readFileSync(path, "utf8"));
}

function writeJson(path, value) {
  const tmpPath = `${path}.tmp`;
  writeFileSync(tmpPath, `${JSON.stringify(value, null, 2)}\n`);
  renameSync(tmpPath, path);
}

function loadState(paths) {
  if (!existsSync(paths.statePath)) {
    throw new Error(`No state file at ${paths.statePath}. Run init first.`);
  }
  return readJson(paths.statePath);
}

function nextReportPath(paths, iteration) {
  return join(
    paths.iterationsDir,
    `${String(iteration).padStart(3, "0")}-report.md`,
  );
}

function init(flags) {
  const paths = statePaths(flags.dir);
  if (existsSync(paths.statePath) && !flags.force) {
    throw new Error(`State already exists at ${paths.statePath}. Use --force to replace it.`);
  }
  mkdirSync(paths.iterationsDir, { recursive: true });
  const state = readJson(templatePath);
  state.goal = String(flags.goal || "");
  if (flags["max-iterations"]) {
    state.charter.budgets.max_iterations = Number(flags["max-iterations"]);
  }
  state.assumptions.push({
    at: new Date().toISOString(),
    text: "Initial state was generated by autopilot-loop CLI. Charter should be refined by the agent before implementation.",
  });
  writeJson(paths.statePath, state);
  console.log(`Initialized ${paths.statePath}`);
}

function candidateScore(task) {
  const impact = Number(task.impact || 0);
  const confidence = Number(task.confidence || 0);
  const evidence = Number(task.evidence || 0);
  const effort = Number(task.effort || 0);
  const risk = Number(task.risk || 0);
  return impact * 3 + confidence * 2 + evidence * 2 + effort + risk;
}

function score(flags) {
  const paths = statePaths(flags.dir);
  const state = loadState(paths);
  state.candidate_tasks = state.candidate_tasks
    .map((task) => ({ ...task, score: candidateScore(task) }))
    .sort((a, b) => b.score - a.score);
  writeJson(paths.statePath, state);
  console.log(JSON.stringify(state.candidate_tasks, null, 2));
}

function report(flags) {
  const paths = statePaths(flags.dir);
  mkdirSync(paths.iterationsDir, { recursive: true });
  const state = loadState(paths);
  state.iteration += 1;
  const reportPath = nextReportPath(paths, state.iteration);
  const summary = String(flags.summary || "Iteration completed.");
  const verification = flags.verification ? String(flags.verification) : "Not recorded.";
  const body = `# Iteration ${state.iteration}

## Summary

${summary}

## Verification

${verification}

## Judge Decision

${state.judge.reason}
`;
  writeFileSync(reportPath, body);
  state.completed.push({
    iteration: state.iteration,
    at: new Date().toISOString(),
    summary,
    report: reportPath,
  });
  state.last_verification = verification === "Not recorded." ? [] : [verification];
  writeJson(paths.statePath, state);
  console.log(`Wrote ${reportPath}`);
}

function judge(flags) {
  const paths = statePaths(flags.dir);
  const state = loadState(paths);
  state.judge = {
    continue: String(flags.continue) === "true",
    confidence: Number(flags.confidence || 0),
    reason: String(flags.reason || ""),
    next_focus: String(flags["next-focus"] || ""),
  };
  writeJson(paths.statePath, state);
  console.log(JSON.stringify(state.judge, null, 2));
}

function help() {
  console.log(`autopilot-loop

Commands:
  init --goal <text> [--dir <path>] [--max-iterations <n>] [--force]
  score [--dir <path>]
  report --summary <text> [--verification <text>] [--dir <path>]
  judge --continue true|false --reason <text> [--confidence <0..1>] [--next-focus <text>] [--dir <path>]
`);
}

const { command, flags } = parseArgs(process.argv.slice(2));

try {
  if (command === "init") init(flags);
  else if (command === "score") score(flags);
  else if (command === "report") report(flags);
  else if (command === "judge") judge(flags);
  else help();
} catch (error) {
  console.error(error.message);
  process.exitCode = 1;
}
